export const COUNTRIES = "COUNTRIES";
export const SEARCHBYID = "SEARCHBYID";
export const CREATEACTIVITY = "CREATEACTIVITY";
export const FILTERCONTINENTS = "FILTERCONTINENTS";
export const ORDERCOUNTRIES = "ORDERCOUNTRIES";